skip-check: 
  - CKV_SECRET_6
  - CKV2_AWS_4
  - CKV2_AWS_29
  - CKV2_AWS_51
  - CKV2_AWS_53
  - CKV2_AWS_61
  - CKV2_AWS_62
  - CKV_AWS_18
  - CKV_AWS_51
  - CKV_AWS_59
  - CKV_AWS_73
  - CKV_AWS_111
  - CKV_AWS_116
  - CKV_AWS_117
  - CKV_AWS_120
  - CKV_AWS_136
  - CKV_AWS_144
  - CKV_AWS_145
  - CKV_AWS_158
  - CKV_AWS_173
  - CKV_AWS_225
  - CKV_AWS_237
  - CKV_AWS_272
  - CKV_AWS_276
  - CKV_AWS_290
  - CKV_AWS_338
  - CKV_AWS_355
  - CKV_AWS_356
  - CKV_TF_1
  - CKV_TF_2
