name: Checkov IaC Scan

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - '*.md'
      - '.gitignore'

  workflow_dispatch:

jobs:
  scan:
    name: Scan
    runs-on: ubuntu-latest
    environment: iac

    permissions:
      id-token: write
      contents: read
      security-events: write
      actions: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Checkov
        run: |
          pip3 install checkov

      - name: Configure AWS credentials
        id: aws-credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
    
      - name: Initialize Terraform
        working-directory: ./tf
        run: terraform init
        
      - name: Plan Terraform
        working-directory: ./tf
        run: |
          terraform plan -var="aws_account_id=${{ secrets.AWS_ACCOUNT }}" -out="tfplan.bin"
          terraform show -json "tfplan.bin" | jq  > "tfplan.json"
    
      - name: Run Checkov
        id: checkov
        working-directory: ./tf
        run: |
          checkov -f tfplan.json -o cli -o sarif --repo-root-for-plan-enrichment ./tf \
          --output-file-path console,results.sarif --config-file .github/checkov.yml \
          --download-external-modules true --enable-secret-scan-all-files 
        
      - name: Upload SARIF file
        id: sarif
        uses: github/codeql-action/upload-sarif@v3
        if: success() || failure()
        with:
          sarif_file: ./tf/results.sarif
