name: Checkov IaC Scan

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - '*.md'
      - '.gitignore'

  workflow_dispatch:

jobs:
  scan:
    name: Scan
    runs-on: ubuntu-latest
    environment: iac

    permissions:
      id-token: write
      contents: write
      security-events: write
      actions: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Checkov
        id: cache-checkov
        uses: actions/cache@v4
        with:
          path: /usr/local/lib/python*/dist-packages
          key: checkov-${{ hashFiles('/usr/lib/python*/dist-packages/**/*.metadata') }}

      - name: Configure AWS credentials
        id: aws-credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install Checkov
        run: |
          pip3 install checkov

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
    
      - name: Cache Terraform
        id: cache-terraform
        uses: actions/cache@v4
        with:
          path: ./tf/.terraform
          key: terraform-${{ hashFiles('**/*.txt') }}

      - name: Initialize Terraform
        working-directory: ./tf
        run: terraform init
        
      - name: Plan Terraform
        working-directory: ./tf
        run: |
          terraform plan -out="tfplan.bin"
          terraform show -json "tfplan.bin" | jq  > "../.github/tfplan.json"
    
      - name: Run Checkov
        id: checkov
        run: |
          checkov -f .github/tfplan.json -o cli -o sarif --repo-root-for-plan-enrichment ./tf \
          --output-file-path console,results.sarif --config-file .github/checkov.yml \
          --download-external-modules true --enable-secret-scan-all-files
        
      - name: Upload SARIF file
        id: sarif
        uses: github/codeql-action/upload-sarif@v3
        if: success() || failure()
        with:
          sarif_file: results.sarif

      - uses: stefanzweifel/git-auto-commit-action@v5
        name: Commit Terraform Plan
        if: success() || failure()
        with:
          commit_message: "Terraform Plan"
          file_pattern: ".github/tfplan.*"
          commit_user_name: fredmerlo
          commit_user_email: fredmerlo@gmail.com
          commit_author: fredmerlo <fredmerlo@gmail.com>
