name: Unit Tests

on:
  push:
    branches:
      - feat**
      - fix**
    paths-ignore:
      - '.github/workflows/**'
      - '*.md'
      - '.gitignore'

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      checks: write
  
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
        
      - name: Install Dependencies
        run: npm install
     
      - name: Run Tests
        run: npm run test-ci
        env:
          JEST_JUNIT_OUTPUT_DIR: "reports"
          JEST_JUNIT_OUTPUT_NAME: "report.xml"
  
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: JEST Tests    
          path: reports/report.xml
          reporter: jest-junit  
